language: node_js
node_js:
  - 12
dist: bionic
before_install:
  - sudo apt-get install -y python-fontforge hugo
  - npm install -g elm@0.19.1 uglify-js
addons:
  apt:
    update: true
git:
  quiet: true
branches:
  only:
  - master
script: bin/ci
deploy:
    provider: pages
    local_dir: public
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    on:
      branch: master