language: node_js
dist: bionic
before_install:
  - sudo apt-get install -y python-fontforge hugo
  - npm install -g elm@elm0.19.0
addons:
  apt:
    update: true
git:
  quiet: true
branches:
  only:
  - master
  - public
script: bin/ci
