#DefaultContentLanguage = "de"
#languageCode = "de"

title = "GEAS — Alice Kober Gesellschaft für die Entzifferung Antiker Schriftsysteme"
theme = "zeas"

baseurl = ""
relativeurls = true

SectionPagesMenu = "main"