DefaultContentLanguage = "en"
languageCode = "en"

title = "GEAS — Alice Kober Gesellschaft für die Entzifferung Antiker Schriftsysteme"
theme = "zeas"

baseurl = ""
relativeurls = true

SectionPagesMenu = "main"

# HACK so that PDF in content/ are included in the site,
# include content/ in staticDir.
staticDir = ["static", "content"]

[markup.goldmark.renderer]
unsafe = true