DefaultContentLanguage = "en"
languageCode = "en"

title = "GEAS — Alice Kober Gesellschaft für die Entzifferung Antiker Schriftsysteme"
theme = "zeas"

baseurl = ""
relativeurls = true

SectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe = true