name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.3'
          extended: true

      - name: Hugo build
        run: hugo --minify

      - name: Checkout Elamicon build
        uses: actions/checkout@v4
        with:
          repository: 'elamicon/elamicon'
          ref: 'build'
          path: 'elamicon-build'

      - name: cleanup Elamicon build
        run: rm -r elamicon-build/.git

      - name: Copy Elamicon build
        run: cp -r elamicon-build public/tool

      - name: Create CNAME file
        run: echo "center-for-decipherment.ch" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
