name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/zeas-site-build:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build:
    runs-on: ubuntu-latest
    needs: build-container
    container:
      image: ghcr.io/${{ github.repository_owner }}/zeas-site-build:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run CI script
      run: ./bin/ci

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
