name: CI

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write

jobs:
  build-container:
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.docker-image.outputs.image }}
    steps:
    - uses: actions/checkout@v4

    - name: Docker meta
      id: docker-image
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/elamicon/zeas-site
        tags: |
          type=ref,event=branch
          type=sha

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull latest image
      run: docker pull ghcr.io/elamicon/zeas-site:latest || true

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/zeas-site-build:latest
        cache-from: ghcr.io/${{ github.repository_owner }}/zeas-site-build:latest

  build:
    runs-on: ubuntu-latest
    needs: build-container
    container:
      image: ghcr.io/${{ github.repository_owner }}/zeas-site-build:latest

    steps:
    - uses: actions/checkout@v4

    - name: Run CI script
      run: ./bin/ci

    - name: Fix permissions
      run: |
        chmod -c -R +rX "public/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
